document.addEventListener("DOMContentLoaded",()=>{const $=s=>document.querySelector(s);const panels=[...document.querySelectorAll("[data-panel]")];const nav=[...document.querySelectorAll("[data-step-nav]")];const form=$("#checkout-form");const service=$("#service");const names={copywriting:"Copywriting","seo-content":"Content Writing & SEO","landing-pages":"Landing Pages & Ads",websites:"Websites & Complex Web","web-applications":"Web Applications & Database Systems","maintenance-uiux":"Maintenance, Improvement & UI/UX","google-ads":"Google Ads","mobile-apps":"Mobile App Development"};const params=new URLSearchParams(location.search);const incoming=params.get("service")||"";const incomingCollection=params.get("collection")||"";const incomingIndustry=params.get("industry")||"";const incomingTier=params.get("tier")||"";if(incoming&&names[incoming])service.value=incoming;const saved=(()=>{try{return JSON.parse(sessionStorage.getItem("bagusin-checkout")||"null")}catch{return null}})();if(saved){Object.entries(saved).forEach(([k,v])=>{const el=document.getElementById(k);if(el&&k!=="terms-agree")el.value=v||""});if(!service.value&&saved.service)service.value=saved.service}const collection=incomingCollection||saved?.collection||"";const industry=incomingIndustry||saved?.industry||"";const tier=incomingTier||saved?.tier||"";const pretty=v=>String(v||"").replace(/[-_]+/g," ").replace(/\b\w/g,m=>m.toUpperCase());const save=()=>{const data={};form.querySelectorAll("input,select,textarea").forEach(el=>{if(el.id&&el.type!=="checkbox")data[el.id]=el.value});data.collection=collection;data.industry=industry;data.tier=tier;try{sessionStorage.setItem("bagusin-checkout",JSON.stringify(data))}catch{}};const guided={
"copywriting":["Asset type yang dibutuhkan","Audience / pembaca","Tone dan brand voice","Existing copy atau reference","Tujuan utama copy"],
"seo-content":["Business / topic","Target audience","Search intent","Target topics / keywords","Existing content or website"],
"landing-pages":["Offer / product","Target audience","Primary conversion goal","Existing copy and visual assets","Traffic or campaign context"],
"websites":["Business type and objective","Pages / content","Key features","Required integrations","Existing website or migration context"],
"web-applications":["Users and roles","Workflow","Data to manage","Core features","Integrations / existing systems"],
"maintenance-uiux":["Existing URL or repository","Problems to fix","Priority","Expected improvement","Access needed for the work"],
"google-ads":["Business and location","Campaign goal","Budget range","Website / landing page","Tracking and conversion context"],
"mobile-apps":["Android / iOS / cross-platform","Users and core features","Login / payment needs","Backend / data","Notifications and integrations"]
};
const updateGuidance=()=>{
 const box=$("#guided-brief"), title=$("#guided-brief-title"), copy=$("#guided-brief-copy"), list=$("#guided-brief-list"), key=service.value;
 const item=(window.BAGUSIN_SERVICE_REGISTRY?.services||[]).find(s=>s.id===key);
 const prompts=guided[key]||item?.requirements||[];
 if(!key||!prompts.length){if(box)box.hidden=true;return}
 box.hidden=false; title.textContent="Helpful context for "+(item?.name||label());
 copy.textContent="Tidak perlu menjawab semuanya. Gunakan poin ini sebagai panduan agar brief lebih mudah dipahami.";
 list.innerHTML=prompts.map(p=>"<li>"+String(p).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))+"</li>").join("");
};
const label=()=>names[service.value]||"Pilih layanan";const updateAside=()=>{$("#aside-service").textContent=label();$("#terms-service").textContent=label();$("#aside-collection").textContent=collection?pretty(collection):"No collection selected";$("#aside-tier").textContent=tier?pretty(tier):"—";const link=$("#service-terms-link");link.href=service.value?"/bagusin/terms/?topic="+encodeURIComponent(service.value):"/bagusin/terms/";const context=$("#collection-context");if(collection){context.hidden=false;$("#collection-context-title").textContent=pretty(collection);$("#collection-context-meta").textContent=(industry?pretty(industry)+" · ":"")+(tier?pretty(tier)+" · ":"")+"Collection context";const base=service.value==="landing-pages"?"/bagusin/landing-pages/collections/detail/":service.value==="websites"?"/bagusin/websites/collections/detail/":"/bagusin/copywriting/collections/detail/";$("#collection-context-link").href=base+"?collection="+encodeURIComponent(collection)+"&industry="+encodeURIComponent(industry)+(tier?"&tier="+encodeURIComponent(tier):"")}else context.hidden=true};const showStep=n=>{panels.forEach(p=>{const on=Number(p.dataset.panel)===n;p.hidden=!on;p.classList.toggle("is-active",on)});nav.forEach(b=>{const x=Number(b.dataset.stepNav);b.classList.toggle("is-active",x===n);b.classList.toggle("is-complete",x<n)});window.scrollTo({top:document.querySelector(".checkout-progress").getBoundingClientRect().top+window.scrollY-90,behavior:"smooth"})};const serviceAvailable=()=>{const item=(window.BAGUSIN_SERVICE_REGISTRY?.services||[]).find(s=>s.id===service.value);if(!item||item.status==="AVAILABLE")return true;const e=$("#brief-error");e.textContent="Layanan ini belum tersedia untuk order langsung. Gunakan Help Me Choose / Consultation untuk membahas kebutuhan dan availability.";service.focus();return false;};
const validateBrief=()=>{if(!serviceAvailable())return false;if(!service.value||!$("#name").value.trim()||!$("#email").value.trim()||!$("#email").validity.valid||!$("#brief").value.trim()){const e=$("#brief-error");e.textContent="Lengkapi layanan, nama, email yang valid, dan kebutuhan sebelum melanjutkan.";form.querySelector(":invalid")?.focus();return false}$("#brief-error").textContent="";save();return true};const review=()=>{const rows=[["Layanan",label()],["Collection",collection?pretty(collection):"—"],["Level",tier?pretty(tier):"—"],["Nama",$("#name").value],["Email",$("#email").value],["Brand / perusahaan",$("#company").value||"—"],["Target waktu",$("#timeline").value||"—"],["Kebutuhan",$("#brief").value]];$("#review-box").innerHTML=rows.map(([a,b])=>"<div class=\"review-row\"><dt>"+a+"</dt><dd>"+String(b).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br>")+"</dd></div>").join("")};document.querySelectorAll("[data-next]").forEach(b=>b.addEventListener("click",()=>{const n=Number(b.dataset.next);if(n===2&&!validateBrief())return;if(n===3){review();save()}if(n===4&&!$("#terms-agree").checked){$("#terms-error").textContent="Centang persetujuan Terms & Conditions untuk melanjutkan.";return}if(n===4)save();showStep(n)}));document.querySelectorAll("[data-back]").forEach(b=>b.addEventListener("click",()=>showStep(Number(b.dataset.back))));nav.forEach(b=>b.addEventListener("click",()=>{const n=Number(b.dataset.stepNav);if(n===1){showStep(1);return}if(n<=2&&validateBrief()){review();showStep(n)}else if(n===3&&validateBrief()){review();showStep(3)}else if(n===4&&$("#terms-agree").checked){showStep(4)}}));service.addEventListener("change",()=>{updateAside();updateGuidance();save()});form.addEventListener("input",save);updateAside();updateGuidance();save()});